### ISSUE TITLE
Pads are editable only to owner and Elgg admins

### ISSUE THREAD

**Issue by thomasyung** [efault/elggpad-lite#7]
If you create a pad, it is only editable by you (the owner) and an Elgg admin. It is only read-only to other Elgg users. Is this an Elgg issue or something in EtherPad Lite?

**Comment by sembrestels** [comment]
It seems an issue, i check it and I say you.

**Comment by thomasyung** [comment]
So the issue is me? I don't understand. Are you not able to reproduce the problem? What is the point of creating an etherpad in Elgg that only the owner can collaborate on with themselves? I am running on Elgg 1.8.3, and I installed the latest ElggPad from GitHub, and I installed the latest EtherPad Lite from GitHub. I am running it all on a Mac OS X server.

**Comment by sembrestels** [comment]
No, you're in the right. It is a several bug. I will try to solve in few days ;)

**Comment by sembrestels** [comment]
The bug has been solved in the last commits:

https://github.com/efault/elggpad-lite/commit/6a5b8ce50be5390dee7ad1d670ef135b3ba6e2ef

Check that last commit in master works for you.

**Comment by thomasyung** [comment]
Thanks. It worked. Looks like you had the write permissions already in
there (commented out). You just uncommented them.

On Tue, Feb 14, 2012 at 2:24 PM, Sem <
reply@reply.github.com

**Comment by sembrestels** [comment]
Great ;)
