### ISSUE TITLE
No write access combobox if pages plugin is not enabled

### ISSUE THREAD

**Issue by nachopavon** [efault/elggpad-lite#8]
If you dont have the pages plugin enabled, the write permissions box does not appear in the create or edit page

**Comment by RiverVanRain** [comment]
Pads and Pages are integrated together.
So need to enable the Pages plugin for the write permissions

**Comment by nachopavon** [comment]
Thanks, but the problem i'm getting now is that write permissions are not working as expected, No matter what write permissions you specify in the pad, only admins or pad creator can have edit permissions. I have seem someone in the elgg community forums with the same problem, are you getting this as well
 I'm openning a new issue with this.

**Comment by nachopavon** [comment]
I found a closed issue with the answer in https://github.com/efault/elggpad-lite/issues/7, I dont know why master does not have this uncommented...
